### ISSUE TITLE
TS3AudioBot egg not working on newest versions of Pterodactyl

### ISSUE THREAD

**Issue by notnorelock** [Bl4ckBirb/pterodactyl-eggs#1]
It's just throwing error 500, that makes me sad.

**Comment by Bl4ckBirb** [comment]
When are you seeing the error 500? When installing or when starting it or while running?
I am running the newest version of Pterodactyl and it works just fine for me.

**Comment by notnorelock** [comment]
While adding egg to pterodactyl.

**Comment by Bl4ckBirb** [comment]
I think i found the issue. @sheltyyy can you give it another try with the version i just updated?

**Comment by Bl4ckBirb** [comment]
Closing this as its done and there has been no update for two months

**Comment by thexnike** [comment]
hEY WHY THIS NOT WORKING I created the server TS3AudioBot and saying - 

Pull complete 
Extracting [==================================================>]     403B/403B
Extracting [==================================================>]     403B/403B
Pull complete 
Digest: sha256:2969a0bf789811fc09625ebe472e23fcab133a26bae2b494ef5a5ec79706a4a1 
Status: Downloaded newer image for ghcr.io/bl4ckbirb/pterodactyl-eggs:ts3audiobot 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ Starting installation process, this could take a few minutes...
exec /bin/ash: exec format error
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from bl4ckbirb/pterodactyl-eggs 
Status: Image is up to date for ghcr.io/bl4ckbirb/pterodactyl-eggs:ts3audiobot 
Digest: sha256:2969a0bf789811fc09625ebe472e23fcab133a26bae2b494ef5a5ec79706a4a1 
[Pterodactyl Daemon]: Finished pulling Docker container image
exec /bin/sh: exec format error
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 255
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from bl4ckbirb/pterodactyl-eggs 
Status: Image is up to date for ghcr.io/bl4ckbirb/pterodactyl-eggs:ts3audiobot 
Digest: sha256:2969a0bf789811fc09625ebe472e23fcab133a26bae2b494ef5a5ec79706a4a1 
[Pterodactyl Daemon]: Finished pulling Docker container image
exec /bin/sh: exec format error
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 255
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
